version: "3.3"
services:
  envoy-proxy:
    build:
      context: .
      dockerfile: ./.docker/envoy/Dockerfile
    networks:
      - statistico_internal
    mem_limit: 1024M
    mem_reservation: 256M
    environment:
      STATISTICO_TRADER_HOST: statistico-trader-grpc
      STATISTICO_TRADER_PORT: 50051
    ports:
      - "9901:9901"
      - "8080:8080"

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: statistico
      POSTGRES_PASSWORD: password
      POSTGRES_DB: statistico_trader
    ports:
      - 5434:5432
    networks:
      - statistico-trader_default

  console: &console
    build:
      dockerfile: ./.docker/Dockerfile
      context: .
    environment:
      DB_DRIVER: postgres
      DB_HOST: postgres
      DB_NAME: statistico_trader
      DB_PASSWORD: password
      DB_USER: statistico
      DB_PORT: 5432
    networks:
      - statistico_internal
      - statistico-trader_default
    tty: true

  queue:
    <<: *console
    command: ["./queue"]

  migrate:
    <<: *console
    command: [ "./bin/migrate" ]

  statistico-trader-grpc:
    <<: *console
    networks:
      - statistico_internal
      - statistico-trader_default
    ports:
      - "50051"
    command: [ "./grpc", "--port 50051" ]

  test:
    build:
      dockerfile: ./.docker/test/Dockerfile
      context: .
    environment:
      DB_DRIVER: postgres
      DB_HOST: postgres
      DB_PASSWORD: password
      DB_NAME: statistico_trader
      DB_USER: statistico
      DB_PORT: 5432
    volumes:
      - .:/opt
    networks:
      - statistico-trader_default

networks:
  statistico-trader_default:
    external: false
  statistico_internal:
    external: true
